name: CI

on: [push]

jobs:
  linux:
    name: Linux ${{ matrix.config.name }}
    runs-on: ubuntu-20.04  # https://github.com/actions/virtual-environments
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: GCC 10,   CC: gcc-10,   CXX: g++-10,     flags: ""}
          - { name: Clang 11, CC: clang-11, CXX: clang++-11, flags: "" }
          - { name: Clang 12, CC: clang-12, CXX: clang++-12, flags: "" }
          - { name: ASan,     CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_ADDRESS=ON" }
          - { name: LSan,     CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_LEAK=ON" }
          - { name: MSan,     CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_MEMORY=ON" }
          - { name: TSan,     CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_THREAD=ON" }
          - { name: UBSan,    CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON" }
    steps:
      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y libbenchmark-dev libsndfile1-dev vamp-plugin-sdk
          pip install conan
      - uses: actions/checkout@v2
      - name: Compile and run tests
        env:
          CC: ${{ matrix.config.CC }}
          CXX: ${{ matrix.config.CXX }}
        run: |
          mkdir build
          cd build
          cmake \
            -DRTVAMP_ENABLE_CONAN=ON \
            -DRTVAMP_ENABLE_BENCHMARKS=ON \
            -DRTVAMP_ENABLE_EXAMPLES=ON \
            -DRTVAMP_ENABLE_TESTS=ON \
            ${{ matrix.config.flags }} \
            ..
          cmake --build .

  # windows:
  #   name: Windows ${{ matrix.config.name }}
  #   runs-on: ${{ matrix.config.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       config:
  #         - { name: Visual Studio 17 2022, os: windows-2022 }
  #   steps:
  #     - name: Install requirements
  #       run: |
  #         pip install conan
  #     - uses: actions/checkout@v2
  #     - name: Compile and run tests
  #       run: |
  #         mkdir build
  #         cd build
  #         cmake -DRTVAMP_ENABLE_CONAN=ON -DRTVAMP_ENABLE_EXAMPLES=ON -DRTVAMP_ENABLE_TESTS=ON ..
  #         cmake --build . --config RelWithDebInfo
