name: CI

on: [push]

jobs:
  linux:
    name: Linux ${{ matrix.config.name }}
    runs-on: ubuntu-20.04  # https://github.com/actions/virtual-environments
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: GCC 10,       CC: gcc-10,   CXX: g++-10,     flags: ""}
          - { name: Clang 11,     CC: clang-11, CXX: clang++-11, flags: "" }
          - { name: Clang 12,     CC: clang-12, CXX: clang++-12, flags: "" }
          - { name: ASan,         CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_ADDRESS=ON" }
          - { name: LSan,         CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_LEAK=ON" }
          - { name: MSan,         CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_MEMORY=ON" }
          - { name: TSan,         CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_THREAD=ON" }
          - { name: UBSan,        CC: clang-12, CXX: clang++-12, flags: "-DRTVAMP_ENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON" }
          - { name: Coverage,     CC: gcc-10,   CXX: g++-10,     flags: "-DRTVAMP_ENABLE_COVERAGE=ON" }
          - { name: Amalgamation, CC: gcc-10,   CXX: g++-10,     flags: "-DRTVAMP_ENABLE_AMALGAMATION=ON" }
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y libbenchmark-dev libsndfile1-dev vamp-plugin-sdk
          pip install conan cpp-coveralls quom
      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: linux-conan-${{ matrix.config.name }}
      - name: Compile and run tests
        env:
          CC: ${{ matrix.config.CC }}
          CXX: ${{ matrix.config.CXX }}
        run: |
          mkdir build
          cd build
          cmake \
            -DRTVAMP_ENABLE_CONAN=ON \
            -DRTVAMP_BUILD_BENCHMARKS=ON \
            -DRTVAMP_BUILD_EXAMPLES=ON \
            -DRTVAMP_BUILD_TESTS=ON \
            ${{ matrix.config.flags }} \
            ..
          cmake --build .
      - name: Upload coverage results to coveralls.io
        if: ${{ github.ref == 'refs/heads/master' && matrix.config.name == 'Coverage' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls \
            -E '.*/3rdparty/.*' \
            -E '.*/benchmarks/.*' \
            -E '.*/build/.*' \
            -E '.*/examples/.*' \
            -E '.*/tests/.*' \
            --gcov-options '\-lp';
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.config.name == 'Amalgamation' }}
        with:
          name: pluginsdk_amalgamated
          path: build/amalgamation/pluginsdk/include/rtvamp/pluginsdk.hpp

  windows:
    name: Windows ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: Visual Studio 17 2022, os: windows-2022 }
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          pip install conan
      - name: Cache Conan packages
        uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: windows-conan-${{ matrix.config.name }}
      - name: Compile and run tests
        run: |
          mkdir build
          cd build
          cmake -DRTVAMP_ENABLE_CONAN=ON -DRTVAMP_BUILD_EXAMPLES=ON -DRTVAMP_BUILD_TESTS=ON ..
          cmake --build . --config RelWithDebInfo
