name: Doc

on:
  push:
    branches:
      - master

jobs:
  doc:
    name: Build Doxygen documentation and upload to GitHub pages
    runs-on: ubuntu-20.04
    steps:
      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build doc with CMake
        run: |
          mkdir build
          cd build
          cmake -DRTVAMP_BUILD_DOCUMENTATION=ON ..
          cmake --build . --target rtvamp-doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/html
