name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  amalgamation:
    name: Amalgamation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          pip install quom
      - name: Generate amalgamated header/source files
        run: |
          mkdir build
          cd build
          cmake -DRTVAMP_ENABLE_AMALGAMATION=ON ..
          cmake --build . --target rtvamp-pluginsdk-amalgamation
      - name: Upload artifcats
        uses: actions/upload-artifact@v3
        with:
          name: pluginsdk_amalgamated
          path: build/amalgamation/pluginsdk/include/rtvamp/pluginsdk.hpp

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: amalgamation
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: pluginsdk_amalgamated
      - name: List files
        run: ls -R
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pluginsdk.hpp
